### ISSUE TITLE
feature: Providers must implement Query Parameters

### ISSUE THREAD

**Issue by raamsri** [tinkershack/meteomunch#13]
# Feature Request

## Summary

Include `SetQueryParams()` method in the Provider interface implementation

## Motivation

As of now, QP is passed as a parameter to `FetchData()` method to implement `Provider` interface. However, this mandates passing QP as an argument for every `FetchData()` call for that Provider client. 
- As the QPs aren't modified frequently for a provider, it would reduce computational space and time when attached to the client struct just once.
- Should the QPs conditionally change, or another use case calls for adhoc changes, a new Provider client may be created with modified QP map.
- Makes the code cleaner, and pragmatic.

## Detailed Design

In `providers` package:
type Provider interface {
	~FetchData(queryParams map[string]string) (*plumber.BaseData, error)~
	FetchData() (*plumber.BaseData, error)
	SetQueryParams(qp map[string]string)
}

In `open_meteo.go`, func `OpenMeteoQueryParams()` must be a method on `OpenMeteoProvider` type.

Similar implementation for the upcoming meteoblue implementation as well.

## Alternatives

Retain the existing design of having independent functions to set QP rather than mandating in the Provider interface.

## Additional Context

None.

## Acceptance Criteria

- [ ] Remove the `queryParams map[string]string` parameter from `FetchData()` method `Provider` interface.
- [ ] Include `SetQueryParams()` method to the `Provider` interface.
- [ ] Make appropriate changes to open-meteo provider to implement the updated `Provider` interface.

## Additional Information

#12 #5

**Comment by raamsri** [comment]
@Yendelevium If this helps, would you like to pick this up?

**Comment by raamsri** [comment]
If you have already started work on MB's data models to suit #12, then perhaps Karthik @adofm  can do this? It's a quick fix.

**Comment by yendelevium** [comment]
@raamsri i haven't yet started, Ill get this done

**Comment by yendelevium** [comment]
In the long run, won't we be taking the coordinates for latitude and longitude from the user? I think we can take *plumber.Coordinates as parameters for both the functions (which we can hardcode for now, and later we can extract them frm either the request headers or the req query-str).. Thoughts @raamsri @adofm ?

**Comment by raamsri** [comment]
Passing it as a function parameter may not be necessary because the co-ordinates are passed in the query params already as all providers expect it as a query parameter. Is there any other reason why you may want it passed as a func parameter nonetheless?

**Comment by raamsri** [comment]
Well, of course, as you figured, the co-ords will be picked from user input and passed as query parameters to the provider.

**Comment by yendelevium** [comment]
> Well, of course, as you figured, the co-ords will be picked from user input and passed as query parameters to the provider.

Yeah this..

**Comment by raamsri** [comment]
You are correct, it makes sense to pass the co-ords to FetchUpdate() so that we can make calls for multiple locations without setting QP every time. 

Let's do that.

**Comment by yendelevium** [comment]
Cool. One more prorblem, for MB we need api key taken frm the config
2 Ways
 - Pass the config to the function, like the coords
 - Call config.New() in providers which need the API KEy

First method, the config will be passed to providers which don't need API keys or anything from the config
Second method, we recall config.New() for every request

I'm divided here because i can't see any proper benefit of one over the other. A better decision could be made if we know the ratio of providers we will be integrating with apikeys to the ones without, or we could go for a different method entirely. Thoughts? @adofm @raamsri

**Comment by raamsri** [comment]
> Cool. One more prorblem, for MB we need api key taken frm the config 2 Ways
> 
>     * Pass the config to the function, like the coords
> 
>     * Call config.New() in providers which need the API KEy
> 
> 
> First method, the config will be passed to providers which don't need API keys or anything from the config Second method, we recall config.New() for every request
> 
> I'm divided here because i can't see any proper benefit of one over the other. A better decision could be made if we know the ratio of providers we will be integrating with apikeys to the ones without, or we could go for a different method entirely. Thoughts? @adofm @raamsri

That's a very relevant and pertinent concern Yash. I've tried something that fixes the problems of the second method which you listed. I haven't had the time to create an appropriate bug report for it but I've described the changes in the Git commit. Please check if this patch sorts out the trouble you spotted?

**Comment by raamsri** [comment]
PR #14
