### ISSUE TITLE
bug: No default config values

### ISSUE THREAD

**Issue by raamsri** [tinkershack/meteomunch#7]
### Problem

1. When Munch config file is absent, config.New() fails silently.
2. There are no defaults set for `config.config` struct returned by `config.New()` when the case is 1. as mentioned above.
3. Referencing atributes within nil `config` will panic.

### What's desired?

`config.New()` must always return a valid config struct. When there's no config provided, it must set and return error appropriately but should still return a default config struct. That means, config.New() always send returns valid `config` in `config, err` even when `err` is set. When `err != nil`, it implies that the config file wasn't passed so the default config has been returned.

### Errors

Silent errors, but fails when the calling function references nil `config` struct. 

```sh
{"time":"2024-10-04T21:30:21.921061+05:30","level":"ERROR","msg":"FAIL","tag":"cmd","err":"find config file"}
{"time":"2024-10-04T21:30:21.921337+05:30","level":"INFO","msg":"Config parsed successfully","tag":"server","config":{"Munch":{"Server":{"Hostname":"","Port":""},"LogLevel":""},"DocumentStore":"","Mongo":{"Name":"","URI":"","DBName":"","DBNumber":0},"DLMRedis":{"Name":"","URI":"","DBName":"","DBNumber":0},"MeteoProviders":null}}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/tinkershack/meteomunch/server.Serve({0xc0000b0720?, 0x501ff20?}, {0x5377820?, 0xfffffffffffffffc?, 0x4e45127?})
        /Users....meteomunch/server/server.go:53 +0x856
github.com/tinkershack/meteomunch/cmd.init.func1(0xc0001a8b00?, {0x5377820, 0x0, 0x0})
        /Users...meteomunch/cmd/server.go:17 +0x76
github.com/spf13/cobra.(*Command).execute(0x5350780, {0x5377820, 0x0, 0x0})
        /Users/raam/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x53504a0)
        /Users/raam/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/raam/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/tinkershack/meteomunch/cmd.Execute()
        /Users..../meteomunch/cmd/root.go:25 +0x1e
main.main()
        /Users/...meteomunch/main.go:8 +0xf
exit status 2
```

### How to reproduce?

1. Rename or remove `munch.yml` config file.
2. Run `go run main.go server`

### Expected output
No error

### Notes/Suggestions

```go
	if err := viper.Unmarshal(conf); err != nil {
		slog.Error(e.FAIL, "err", err, "description", "Couldn't parse config")
		return nil, err
	}
```
This doesn't seem to set `err` even when the config file is missing. Handle setting defaults appropriately.

**Note**: `cmd/root.go` line 62, `viper.ReadInConfig()` does return error on missing config but we don't panic there because we will handle that logic of setting defaults in `config` package. `cmd` package merely acknowledges and logs that the file wasn't passed. That's deliberate: we will not set default config using `Viper.SetDefault()` within `cmd` because then it becomes redundant to enforce config schema here again while the control of the schema belongs to `config` package; it'll be dirty catch-up game.

**Comment by JrGkOG** [comment]
@raamsri 

When it starts and it detects that the config file is missing, should we create a config file with default values, or is it preferable to provide the default values directly within the code?

I believe creating a new default config file might be a better because it allows users to see all available configuration options and modify them easily if needed

**Comment by raamsri** [comment]
Creating a new default config file will be a nasty surprise for the users of Munch in many levels. Perhaps I'll take the time to illustrate a couple or so @adofm 
For one instance, the values are not known until the process/package has already kick started, which may not be desired. Besides that, writing a config file should never be done by the program/package that is dependent on those values to bootstrap the service. After all, this can lead to unnecessary cases in which if the config wasn't provided by the user and then Munch puts a default config file on the disk but later the user creates a new config file and has also edited the default config. Now on a service restart or a new package instantiation, you'll be battling the precedence of reading which of those ten thousand different config files and race cases and choices over "should we overwrite an existing default config file or should we create another ten thousand. And, a ten thousand new decisions on how to make the file names unique and to check which one was modified the latest and modified by who and repeat this for each restart"

Catch the drift?

**Comment by raamsri** [comment]
Let's try something along the lines of differentiating critical vs non-critical config values? 
- If the critical values are absent, we must panic and exit. That would also include config validations that fail.
- Non critical fields can be defaulted when it's not explicitly provided by the user. 

For instance, Munch.LogLevel and Munch.Server values are non-critical. So far the config has only contained non critical values. Even when no meteo providers are listed in the config, we can default to a provider that doesn't ask for an API key, and allows open access. 

All of these can be set and handled in the code and clearly documented in the config package, particularly config.New() function.

**Comment by raamsri** [comment]
What are your thoughts? @Yendelevium @adofm

**Comment by JrGkOG** [comment]
Great idea @raamsri 

so based on critical and non-critical values we determine what defaults to be set.

So we might come to a point where now a value might not be critical but in future it turns out to be critical so we make sure that we incorporate those also.

**Comment by yendelevium** [comment]
Yeah I think that looks good too. I can't really think of anything better.

**Comment by JrGkOG** [comment]
This issue can be closed right ?
